name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ecosystem:
    uses: angr/ci-settings/.github/workflows/angr-ci.yml@master

  test:
    name: Test
    strategy:
      matrix:
        os: 
#          - macos-15-intel
#          - macos-15
#          - ubuntu-24.04
          - windows-11-arm
          - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - name: Activate msvc
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
        if: startsWith(runner.os, 'windows')
      - name: Setup uv
        uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6
      - name: Sync dependencies
        run: uv sync -p 3.12
      - name: Run tests
        run: uv run pytest tests

      - name: Build wheel and source distribution
        run: uv build
  
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-packages
          path: dist/
          if-no-files-found: error
